### PR TITLE
add default value to lazy blueprint

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
This repo appears to be dead?

**Comment by kellyselden** [comment]
Maybe I'm misunderstanding. Is the in-repo-engine blueprint duplicated here?

**Comment by trentmwillis** [comment]
@kellyselden it's not dead. This repo allows you to create a new _standalone_ Engine (similar to how you create a new Glimmer app) whereas the `ember-engines` addon contains the blueprint for an `in-repo` Engine.

**Review by trentmwillis — APPROVED** [review]

**Comment by kellyselden** [comment]
@trentmwillis OK I see. Have you thought of consolidating some of the redundancy?

**Comment by trentmwillis** [comment]
I haven't been actively thinking about any of this. Potentially we could consolidate everything here and set this as a dependency of ember-engines.

**Pull request merged**
